apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-dep
  namespace: libapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-label
  template:
    metadata:
      labels:
        app: auth-label
    spec:
      containers:
        - name: auth_service
          image: mmunna431/py-app:authimage
          ports:
            - containerPort: 5001
      imagePullSecrets:
      - name: db-secret
