apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-dep
  namespace: libapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-label
  template:
    metadata:
      labels:
        app: book-label
    spec:
      containers:
        - name: book_service
          image: mmunna431/py-app:bookimage
          ports:
            - containerPort: 5002
