apiVersion: apps/v1
kind: Deployment
metadata:
  name: borrow-dep
  namespace: libapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: borrow-label
  template:
    metadata:
      labels:
        app: borrow-label
    spec:
      containers:
        - name: borrow-service
          image: mmunna431/py-app:borrowimage
          ports:
            - containerPort: 5003
          env:
            - name: DB_USERNAME
              valueFrom:
              secretKeyRef:
                name: db-secret
                key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password

