apiVersion: apps/v1
kind: Deployment
metadata:
  name: borrow-dep
  namespace: libapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: borrow-label
  template:
    metadata:
      labels:
        app: borrow-label
    spec:
      containers:
        - name: borrow_service
          image: mmunna431/py-app:borrowimage
          ports:
          - containerPort: 5003
