apiVersion: apps/v1
kind: Statefulset
metadata:
  name: db-dep
  namespace: libapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-label
  template:
    metadata:
      labels:
        app: db-label
    spec:
      containers:
        - name: db
          image: mmunna431/py-app:db
          ports:
            - containerPort: 3306
      imagePullSecrets:
      - name: db-secret
