apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-dep
  namespace: libapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-label
  template:
    metadata:
      labels:
        app: db-label
    spec:
      containers:
        - name: db
          image: mmunna431/py-app:db
          ports:
            - containerPort: 3306
          env:
            - name: DB_USERNAME
              valueFrom:
              secretKeyRef:
                name: db-secret
                key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password

