#generate code for hpa for the all  deployment files
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app-hpa
  namespace: libapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-dep
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: auth-hpa
  namespace: libapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auth-dep
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: borrow-hpa
  namespace: libapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: borrow-dep
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: book-hpa
  namespace: libapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: book-dep
  minReplicas: 2
  maxReplicas: 5  
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: db-hpa
  namespace: libapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: db-dep
  minReplicas: 2
  maxReplicas: 5  
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
